---
- name: create directory for Jacket
  file:
    path: /opt/Jackett
    state: directory
    mode: '0755'

# - name: Download jackett binary
#   get_url:
#     url: https://github.com/Jackett/Jackett/releases/download/v0.16.899/Jackett.Binaries.Mono.tar.gz
#     dest: /opt/Jackett
#     mode: '0440'

- name: Download and Unarchive Jackett
  unarchive:
    src: https://github.com/Jackett/Jackett/releases/download/v0.16.899/Jackett.Binaries.Mono.tar.gz
    dest: /opt/
    remote_src: yes

- name: Recursively change ownership of the Jackett directory
  file:
    path: /opt/Jackett
    state: directory
    recurse: yes
    owner: giovas
    group: giovas

- name: "Template for jackett service"
  template:
    src: jackett.service.j2
    dest: /etc/systemd/system/jackett.service
    owner: root
    group: root
    mode: '0777'

- name: 'enable at startup and start jackett.service daemon'
  service:
    name: jackett.service
    enabled: yes
    state: started

- name: additional reminders
  debug:
    msg: >
         View Jackett at http://<yourhostname>:9117/UI/Dashboard
         NOTE: Jackett's UI is unsecured by default, scroll down and set an admin password before you do anything else.
         Add a bunch of public indexers, and leave the tab open for use to configure Sonarr/Radarr