---
- name: "Add an apt key by id from a keyserver"
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF


- name: "add monodevelop repository prerequisite"
  apt_repository:
    repo: "deb http://download.mono-project.com/repo/ubuntu {{ ansible_distribution_release }} main"
    state: present

- name: "install dependency packages"
  apt:
    name:
      - mono-devel
      - mediainfo
      - sqlite3
      - libmono-cil-dev
      - curl 
      - ca-certificates-mono
      - libcurl4-openssl-dev
    update_cache: yes
    state: present

- name: "install deluge"
  import_tasks: deluge.yml
  tags: deluge

- name: "install jackett"
  import_tasks: jackett.yml
  tags: jackett

- name: "install radarr"
  import_tasks: radarr.yml
  tags: radarr

- name: "install sonarr"
  import_tasks: sonarr.yml
  tags: sonarr

- name: install plex
  block:
   - name: Download and Unarchive Plex
     apt:
      deb: https://downloads.plex.tv/plex-media-server-new/1.19.5.3112-b23ab3896/debian/plexmediaserver_1.19.5.3112-b23ab3896_amd64.deb

   - name: additional reminders
     debug:
       msg: >
              View Plex at http://<yourhostname>:32400/web/index.html (The Plex service auto-starts by default)
              Plex is unsecured by default, but should prompt you to "claim" your server with a Plex account on first login.
              Set up Plex to watch directories where media is managed by Sonarr and Radarr.
              For first-time Plex setup, you must access the Plex UI from the same subnet as the server. If it is a remote server
              and that's not possible, you'll need to do the first-time setup through an SSH tunnel
              From your local machine
              ssh ip.address.of.server -L 8888:localhost:32400
  tags: plex

