---
- hosts: all 
  become: yes

  vars:
    media_dir: '/home/giovas/media'
    users:
      - name: giovas
        passwd: belial
   
  tasks:
    - name: "install express prerequisites"
      apt:
        update_cache: yes
        name: xz-utils
        state: present

    - name: Install express vpn package from the internet.
      apt:
        deb: https://download.expressvpn.xyz/clients/linux/expressvpn_2.4.5.2-1_amd64.deb

