---
- hosts: all 
  become: no

  tasks:
    # - name: "test1"
    #   debug: 
    #    msg: "{{ inventory_hostname }}"
    # - name: "test2"
    #   debug: 
    #    var: ansible_hostname
    # - name: "test 3"
    #   debug: 
    #     var: hostvars
    - name: "test4"
      debug: 
        msg: "distro {{ ansible_distribution }} and version  {{ ansible_distribution_release }}"
    - name: "test 5"
      debug: 
        msg: " la llave es: {{ xmr_key }}"
