---

  
  
- name: "use custom postgres-common logrotate(8) file if required"
  template:
    src: "custom_logrotate_config_postgresql-common.j2"
    dest: "/etc/logrotate.d/postgresql-common"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  when: postgresql_common_custom_log_rotation_needed
  tags:
    - configuration
    - logrotate
    - install_postgres