---
# try and follow https://docs.docker.com/engine/install/ubuntu/
- name: "install Docker CE prerequisites"
  apt:
    pkg: ["apt-transport-https", "ca-certificates", "curl","software-properties-common", "gnupg-agent"]
    state: present
    update_cache: yes

- name: Add an Docker oficcial key 
  apt_key:
    keyserver: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable" 
    state: present    

- name: "install Docker packages"
  apt:
    pkg: ["docker-ce=5:18.09.8~3-0~ubuntu-bionic","docker-ce-cli=5:19.03.5~3-0~ubuntu-bionic", "containerd.io","docker-compose"]
    state: present
    update_cache: yes

- name: "add docker_users to docker group"
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"
  when: docker_users is defined
  ignore_errors: "{{ ansible_check_mode }}"    
   
# - name: "install Ansible docker_container dependencies"
#   pip:
#     name: docker-py
#     version: 1.9.0